# Generated by Django 2.2 on 2023-04-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lashstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
